#########################################################
#Let greeves12 change this for each UHC server, thanks
server-id: 1
#########################################################
#Change the header
header: "&2&lRecon&f&l-&4&lNetwork"
#Change the footer
footer: "&dServer ID # %id%"
#########################################################
#MySQL configuration
MySQL:
  Username: Username
  Password: Password
  Ip: 0.0.0.0
  Database: Database
#########################################################
#World border setting for UHC
x: -676
z: -663
#########################################################